name: Run Tests

on:
  pull_request:
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'src/**'
  push:
    branches:
      - main
      - master

jobs:
  run-tests:
    strategy:
      fail-fast: true
      matrix:
        os: [windows-2019, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Run checkout
        uses: actions/checkout@v4

      - name: pester
        run: Invoke-Pester -Show All

      - name: Install Security Module
        run: Import-Module Microsoft.PowerShell.Security

      - name: go test
        run: |
          $env:PSModulePath = ''
          go test -v ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6.1.0
        with:
          args: --timeout=10m
          version: v1.59
